Repository huwzpf/parallel-processing-cpu-and-gpu-env-and-lib-with-powercap, pull requests merged in 2024-10, with the labels that each got.

#57 Fix ssh config guide
  doc/InstrukcjaKASK.md
Labels: documentation, please merge

#59 Update documentation regarding SSH
  doc/InstrukcjaKASK.md
  doc/InstrukcjaSSH.md
Labels: documentation

#50 Fix cpu power
  cudampilib/cudampilib.c
  cudampilib/cudampislave.c
Labels: bug

#58 Fix tmp issue
  cudampilib/cudampicommon.c
Labels: bug

#66 Add connection check script
  cudampilib/check_connection.sh
Labels: enhancement, ready to review

#61 Refactor run script
  cudampilib/debughostfile
  cudampilib/hostfile
  cudampilib/run_scripts/run-app
  cudampilib/run_scripts/run-streams-collatz
  cudampilib/run_scripts/run-streams-collatz-debug
  cudampilib/run_scripts/run-streams-patternsearch
  cudampilib/run_scripts/run-streams-patternsearch-debug
  cudampilib/run_scripts/run-streams-vecadd
  cudampilib/run_scripts/run-streams-vecadd-debug
  cudampilib/run_scripts/run-streams-vecmaxdiv
  cudampilib/run_scripts/run-streams-vecmaxdiv-debug
Labels: refactor, ready to review

#78 Update with simplified guide using check_connection.sh script
  doc/InstrukcjaSSH.md
Labels: documentation, ready to review

#73 Adjust apps to async cpu streams
  .gitignore
  cudampilib/apps/app/app.c
  cudampilib/apps/collatz/app-streams-collatz.c
  cudampilib/apps/patternsearch/app-streams-patternsearch.c
  cudampilib/apps/vecadd/app-streams-vecadd.c
  cudampilib/apps/vecadd/vecadd_defines.h
  cudampilib/apps/vecmaxdiv/app-streams-vecmaxdiv.c
  cudampilib/check_apps_outputs.sh
  cudampilib/hostfile
  cudampilib/include/utility.h
Labels: refactor, ready to review

#65 Implement asynchronous cudaMemcpyAsync on slaves using cpu task mechanism
  cudampilib/cudampilib.c
  cudampilib/cudampislave.c
  cudampilib/include/cudampi.h
Labels: enhancement
